# Generated by Django 5.1.1 on 2024-10-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='user_id',
        ),
        migrations.AlterModelTable(
            name='mymodel',
            table='tbl_addressbook',
        ),
    ]
